swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
          examples:
            application/json:
              status: 200
              message: "Profile retrieved successfully"
              body:
                id: "12345"
                email: "user@example.com"
                userName: "johndoe"
        '400':
          description: Invalid request parameters
          examples:
            application/json:
              status: 400
              message: "Invalid request fields"
        '401':
          description: Unauthorized access, token missing or invalid
          examples:
            application/json:
              status: 401
              message: "Unauthorized: Invalid or missing token"
        '500':
          description: Internal server error
          examples:
            application/json:
              status: 500
              message: "An unexpected error occurred"
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile
      description: API for updating user profile attributes
      parameters:
        - in: body
          name: body
          description: Updated user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
          examples:
            application/json:
              status: 200
              message: "Profile updated successfully"
        '400':
          description: Invalid input fields
          examples:
            application/json:
              status: 400
              message: "Invalid request body"
        '401':
          description: Unauthorized access, token missing or invalid
          examples:
            application/json:
              status: 401
              message: "Unauthorized: Invalid or missing token"
        '500':
          description: Internal server error
          examples:
            application/json:
              status: 500
              message: "An unexpected error occurred"
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Fetch User Transactions
      description: Returns all transactions for the current month
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
          examples:
            application/json:
              status: 200
              message: "Transactions retrieved successfully"
              body:
                transactions:
                  - id: "txn123"
                    date: "2024-11-01T14:30:00Z"
                    description: "Grocery shopping"
                    amount: 50.75
                    category: "Food"
                    transactionType: "Debit"
        '400':
          description: Invalid query parameters
          examples:
            application/json:
              status: 400
              message: "Invalid query parameters"
        '401':
          description: Unauthorized access, token missing or invalid
          examples:
            application/json:
              status: 401
              message: "Unauthorized: Invalid or missing token"
        '500':
          description: Internal server error
          examples:
            application/json:
              status: 500
              message: "An unexpected error occurred"

/user/transactions/{transactionId}:
  get:
    security:
      - Bearer: []
    tags:
      - Transaction Module
    summary: Fetch Specific Transaction
    parameters:
      - name: transactionId
        in: path
        required: true
        description: ID of the transaction
        schema:
          type: string
    responses:
      '200':
        description: Transaction retrieved successfully
        schema:
          $ref: '#/definitions/ApiResponse'
        examples:
          application/json:
            status: 200
            message: "Transaction retrieved successfully"
            body:
              id: "txn123"
              date: "2024-11-01T14:30:00Z"
              description: "Grocery shopping"
              amount: 50.75
              category: "Food"
              transactionType: "Debit"
      '400':
        description: Invalid transaction ID
        examples:
          application/json:
            status: 400
            message: "Invalid transaction ID"
      '404':
        description: Transaction not found
        examples:
          application/json:
            status: 404
            message: "Transaction not found"
      '401':
        description: Unauthorized access, token missing or invalid
        examples:
          application/json:
            status: 401
            message: "Unauthorized: Invalid or missing token"
      '500':
        description: Internal server error
        examples:
          application/json:
            status: 500
            message: "An unexpected error occurred"

  put:
    security:
      - Bearer: []
    tags:
      - Transaction Module
    summary: Edit Transaction
    parameters:
      - name: transactionId
        in: path
        required: true
        description: ID of the transaction to edit
        schema:
          type: string
      - in: body
        name: body
        description: Updated transaction details
        required: true
        schema:
          $ref: '#/definitions/TransactionUpdateInput'
    responses:
      '200':
        description: Transaction updated successfully
        schema:
          $ref: '#/definitions/ApiResponse'
        examples:
          application/json:
            status: 200
            message: "Transaction updated successfully"
      '400':
        description: Invalid transaction details
        examples:
          application/json:
            status: 400
            message: "Invalid transaction details"
      '401':
        description: Unauthorized access, token missing or invalid
        examples:
          application/json:
            status: 401
            message: "Unauthorized: Invalid or missing token"
      '404':
        description: Transaction not found
        examples:
          application/json:
            status: 404
            message: "Transaction not found"
      '500':
        description: Internal server error
        examples:
          application/json:
            status: 500
            message: "An unexpected error occurred"

      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionUpdateInput:
    type: object
    properties:
      category:
        type: string
        enum: [Food, Transport, Housing, Utilities, Clothing, Healthcare, Entertainment, Other]
        description: Category of the transaction
      notes:
        type: string
        description: Additional notes for the transaction
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
      transactionType:
        type: string
        enum: [Debit, Credit]
      category:
        type: string
      notes:
        type: string

